# Generated by Django 2.0 on 2018-02-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=2048, unique=True)),
                ('FoundDateTime', models.DateTimeField(auto_now_add=True)),
                ('LastScanDate', models.DateTimeField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.PositiveIntegerField(default=0)),
                ('PagesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Pages')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='personpagerank',
            name='PersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Persons'),
        ),
        migrations.AddField(
            model_name='pages',
            name='SitesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Sites'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='PersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Persons'),
        ),
    ]
