# Generated by Django 2.0 on 2018-02-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048, unique=True)),
                ('found_date_time', models.DateTimeField(auto_now_add=True)),
                ('last_scan_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Pages')),
            ],
            options={
                'db_table': 'person_page_rank',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.AddField(
            model_name='personpagerank',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Persons'),
        ),
        migrations.AddField(
            model_name='pages',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Sites'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Persons'),
        ),
    ]
