# Generated by Django 2.0 on 2018-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='LastScanDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
